const dummy = [
  {
    id: 1,
    name: '금로 파크',
    age: 25,
    job_title: 'S전자 엔지니어',
    location: '#서울 #경기 #인천',
    profile_image_url: '/people/11.jpg',
    images: [
      { id: 0, imageUrl: '/people/11.jpg' },
      { id: 1, imageUrl: '/people/12.jpg' },
      { id: 2, imageUrl: '/people/13.jpg' },
      { id: 3, imageUrl: '/people/14.jpg' },
    ],
  },
  {
    id: 2,
    name: '뿔없는 악어',
    age: 32,
    job_title: '배우',
    location: '#강릉 #강원도',
    profile_image_url: '/people/21.jpg',
    images: [
      { id: 0, imageUrl: '/people/21.jpg' },
      { id: 1, imageUrl: '/people/22.jpg' },
      { id: 2, imageUrl: '/people/23.jpg' },
      { id: 3, imageUrl: '/people/24.jpg' },
    ],
  },
  {
    id: 3,
    name: '라이온맨',
    age: 42,
    job_title: '프로게이머',
    location: '#서울 #경기',
    profile_image_url: '/people/31.jpg',
    images: [
      { id: 0, imageUrl: '/people/31.jpg' },
      { id: 1, imageUrl: '/people/32.jpg' },
      { id: 2, imageUrl: '/people/33.jpg' },
      { id: 3, imageUrl: '/people/34.jpg' },
    ],
  },
  {
    id: 4,
    name: '김철룡',
    age: 23,
    job_title: '헤어 디자이너',
    location: '#강남 #하남',
    profile_image_url: '/people/41.jpg',
    images: [
      { id: 0, imageUrl: '/people/41.jpg' },
      { id: 1, imageUrl: '/people/42.jpg' },
      { id: 2, imageUrl: '/people/43.jpg' },
      { id: 3, imageUrl: '/people/44.jpg' },
    ],
  },
  {
    id: 5,
    name: '마장동 고찬석',
    age: 24,
    job_title: '전문직',
    location: '#세종 #마포 #서울',
    profile_image_url: '/people/51.jpg',
    images: [
      { id: 0, imageUrl: '/people/51.jpg' },
      { id: 1, imageUrl: '/people/52.jpg' },
      { id: 2, imageUrl: '/people/53.jpg' },
      { id: 3, imageUrl: '/people/54.jpg' },
    ],
  },
  {
    id: 6,
    name: '박근호',
    age: 25,
    job_title: '공무원',
    location: '#부산 #서면',
    profile_image_url: '/people/61.jpg',
    images: [
      { id: 0, imageUrl: '/people/61.jpg' },
      { id: 1, imageUrl: '/people/62.jpg' },
      { id: 2, imageUrl: '/people/63.jpg' },
      { id: 3, imageUrl: '/people/64.jpg' },
    ],
  },
];

export default dummy;
