const dummy = [
  {
    id: '88888888-4444-4444-4444-aaaaa0000000',
    email: 'fake@fake.com0',
    phone: '000-0000-0000',
    registered_at: '2024-02-12T04:14:46.425772+00:00',
    profile_veil_img_url:
      'https://ponaaaebmrmbgisdhbrx.supabase.co/storage/v1/object/public/profileImages/1.jpg',
    mbti: 'INTP',
    job_status: '고민중',
    self_description: '반갑습니다 저는 가짜사람입니다 좋은만남 가져봐요',
    region1: '대전',
    region2: '',
    field: '예술',
    name: '김카페',
  },
  {
    id: '88888888-4444-4444-4444-aaaaa0000001',
    email: 'fake@fake.com1',
    phone: '000-0000-0001',
    registered_at: '2024-02-12T05:34:53.282901+00:00',
    profile_veil_img_url:
      'https://ponaaaebmrmbgisdhbrx.supabase.co/storage/v1/object/public/profileImages/2.jpg',
    mbti: 'ENTP',
    job_status: '학생',
    self_description: '반갑습니다 저는 가짜사람입니다~ ㅎㅎㅎ',
    region1: '서울',
    region2: '대전',
    field: '공학',
    name: '홍길동',
  },
  {
    id: '88888888-4444-4444-4444-aaaaa0000002',
    email: 'fake@fake.com2',
    phone: '000-0000-0002',
    registered_at: '2024-02-12T03:14:46.425772+00:00',
    profile_veil_img_url:
      'https://ponaaaebmrmbgisdhbrx.supabase.co/storage/v1/object/public/profileImages/3.jpg',
    mbti: 'INTJ',
    job_status: '직장인',
    self_description: '저는 가짜사람입니다~ ㅠㅠ',
    region1: '전남',
    region2: '광주',
    field: '사업',
    name: '눈뜬두더지',
  },
  {
    id: '88888888-4444-4444-4444-aaaaa0000003',
    email: 'fake@fake.com3',
    phone: '000-0000-0003',
    registered_at: '2024-02-12T04:34:53.282901+00:00',
    profile_veil_img_url:
      'https://ponaaaebmrmbgisdhbrx.supabase.co/storage/v1/object/public/profileImages/4.jpg',
    mbti: 'ENFP',
    job_status: '학생',
    self_description: '카페가는거 좋아해요 저는 가짜사람입니다~',
    region1: '전북',
    region2: '전주',
    field: '교육',
    name: '코없는코끼리',
  },
  {
    id: '88888888-4444-4444-4444-aaaaa0000004',
    email: 'fake@fake.com4',
    phone: '000-0000-0004',
    registered_at: '2024-02-12T02:14:46.425772+00:00',
    profile_veil_img_url:
      'https://ponaaaebmrmbgisdhbrx.supabase.co/storage/v1/object/public/profileImages/5.jpg',
    mbti: 'ENFJ',
    job_status: '프리랜서',
    self_description: '동물원가는거 좋아해요 저는 가짜사람입니다',
    region1: '경기',
    region2: '서울',
    field: '예술',
    name: '발없는말',
  },
];

// const dummy = [
//   {
//     id: 1,
//     name: '금로 파크',
//     age: 25,
//     job_title: 'S전자 엔지니어',
//     location: '#서울 #경기 #인천',
//     profile_image_url: '/people/11.jpg',
//     images: [
//       { id: 0, imageUrl: '/people/11.jpg' },
//       { id: 1, imageUrl: '/people/12.jpg' },
//       { id: 2, imageUrl: '/people/13.jpg' },
//       { id: 3, imageUrl: '/people/14.jpg' },
//     ],
//   },
//   {
//     id: 2,
//     name: '뿔없는 악어',
//     age: 32,
//     job_title: '배우',
//     location: '#강릉 #강원도',
//     profile_image_url: '/people/21.jpg',
//     images: [
//       { id: 0, imageUrl: '/people/21.jpg' },
//       { id: 1, imageUrl: '/people/22.jpg' },
//       { id: 2, imageUrl: '/people/23.jpg' },
//       { id: 3, imageUrl: '/people/24.jpg' },
//     ],
//   },
//   {
//     id: 3,
//     name: '라이온맨',
//     age: 42,
//     job_title: '프로게이머',
//     location: '#서울 #경기',
//     profile_image_url: '/people/31.jpg',
//     images: [
//       { id: 0, imageUrl: '/people/31.jpg' },
//       { id: 1, imageUrl: '/people/32.jpg' },
//       { id: 2, imageUrl: '/people/33.jpg' },
//       { id: 3, imageUrl: '/people/34.jpg' },
//     ],
//   },
//   {
//     id: 4,
//     name: '김철룡',
//     age: 23,
//     job_title: '헤어 디자이너',
//     location: '#강남 #하남',
//     profile_image_url: '/people/41.jpg',
//     images: [
//       { id: 0, imageUrl: '/people/41.jpg' },
//       { id: 1, imageUrl: '/people/42.jpg' },
//       { id: 2, imageUrl: '/people/43.jpg' },
//       { id: 3, imageUrl: '/people/44.jpg' },
//     ],
//   },
//   {
//     id: 5,
//     name: '마장동 고찬석',
//     age: 24,
//     job_title: '전문직',
//     location: '#세종 #마포 #서울',
//     profile_image_url: '/people/51.jpg',
//     images: [
//       { id: 0, imageUrl: '/people/51.jpg' },
//       { id: 1, imageUrl: '/people/52.jpg' },
//       { id: 2, imageUrl: '/people/53.jpg' },
//       { id: 3, imageUrl: '/people/54.jpg' },
//     ],
//   },
//   {
//     id: 6,
//     name: '박근호',
//     age: 25,
//     job_title: '공무원',
//     location: '#부산 #서면',
//     profile_image_url: '/people/61.jpg',
//     images: [
//       { id: 0, imageUrl: '/people/61.jpg' },
//       { id: 1, imageUrl: '/people/62.jpg' },
//       { id: 2, imageUrl: '/people/63.jpg' },
//       { id: 3, imageUrl: '/people/64.jpg' },
//     ],
//   },
// ];
//
export default dummy;
